services:
# https://symfony.com/doc/current/session/locale_sticky_session.html
#  App\profile\subscriber\LocaleSubscriber:
#    arguments: ['%kernel.default_locale%']

#    App\skeleton\entity\ProfileEntity:
#        class: App\profile\entity\Profile
